Pildigalerii/Pildigalerii/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pildigalerii.Models;



namespace Pildigalerii.Controllers
{


    public class AlbumsController : Controller
    {
        private TagaridaEntities db = new TagaridaEntities();
        
        // GET: Albums
        //public ActionResult Index()

        //{
        //    var albums = db.Albums.Include(a => a.Person);
        //    if (Request.IsAuthenticated)
        //        return View(albums.ToList());
        //    else return RedirectToAction("IndexPublic");

        //}

        // GET: Public albums
        public ActionResult Index(string sortOrder)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.OmanikSortParm = String.IsNullOrEmpty(sortOrder) ? "omanik_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var albums = from s in db.Albums.Where(x => x.Access == "public").Include(a => a.Person)
                        select s;
            switch (sortOrder)
            {
                case "name_desc":
                    albums = albums.OrderByDescending(s => s.Title);
                    break;
                case "omanik_desc":
                    albums = albums.OrderByDescending(s => s.OwnerId);
                    break;
                case "Date":
                    albums = albums.OrderBy(s => s.Created);
                    break;
                case "date_desc":
                    albums = albums.OrderByDescending(s => s.Created);
                    break;
                default:
                    albums = albums.OrderBy(s => s.Title);
                    break;
            }
            return View(albums.ToList());
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }

            //missugused pildid  on olemas
            //ViewBag.AlbumImgs = db.Posts.Where(y => y.AlbumId == album.Id).ToList();
            ViewBag.AlbumImgs = album.Posts.OrderByDescending(item => item.Created).ToList();


            return View(album);
        }

        // GET: Albums/Create
        public ActionResult Create()
        {
            ViewBag.OwnerId = new SelectList(db.People, "Id", "Fullname");

            //kes on praegu sisse loginud
           int personId = Person.CurrentUserID(User.Identity.Name);
            ViewBag.UserName = db.People.Where(x => x.Id == personId);

            Album album = new Album { OwnerId = personId, Created = DateTime.Today, Access = "public" }; // ilma access publicuta ei lase creatida

            return View(album);
        }

        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,OwnerId,Access,Created")] Album album)
        {
            if (Request.IsAuthenticated)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        db.Albums.Add(album);
                        db.SaveChanges();
                        return RedirectToAction("MinuUser", "Home");
                    }

                    ViewBag.OwnerId = new SelectList(db.People, "Id", "FullName", album.OwnerId);
                    return View(album);
                }
                catch (Exception)
                {

                    throw;
                }
            }

            else return RedirectToAction("Index");
        }

        // GET: Albums/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.OwnerId = new SelectList(db.People, "Id", "FullName", album.OwnerId);

            //missugused pildid  on olemas
            //ViewBag.AlbumImgs = db.Posts.Where(y => y.AlbumId == album.Id).ToList();
            ViewBag.AlbumImgs = album.Posts.OrderByDescending(item => item.Created).ToList();

            return View(album);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,OwnerId,Access")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                db.Entry(album).Property("Created").IsModified = false; // seda oli vaja, et datetime ei viskaks errorit, kuna SQL ei suuda convertida datetime2 -> datetime
                //db.Entry(album).Property("Access").IsModified = false; //seda ära tagasi sisse kommenteeri, muidu ei salvesta andmebaasi privaatsuse (access) muudatust, kui muuta.
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OwnerId = new SelectList(db.People, "Id", "FullName", album.OwnerId);
            return View(album);
        }

        // GET: Albums/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Album album = db.Albums.Find(id);
            DeletePosts(album);
            db.Albums.Remove(album);
            db.SaveChanges();
            if (Request.IsAuthenticated)
                return RedirectToAction("MinuUser", "Home");
            else
                return RedirectToAction("Index");
        }

        // Kustutab ka need postitused ära, mis selle albumi sees on

        private void DeletePosts(Album a)
        {
            if (a.Posts != null && a.Posts.Count > 0)
            {
                db.Posts.RemoveRange(a.Posts);
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public class Time
        {
            private DateTime _date = DateTime.Now;

            public int ID { get; set; }

            public DateTime DateCreated
            {
                get { return _date; }
                set { _date = value; }
            }

        }
    }
}

Pildigalerii/Pildigalerii/Views/Albums/Create.cshtml
@model Pildigalerii.Models.Album

@{
    ViewBag.Title = "Create";
}

<h2>Lisa uus album</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.OwnerId, "OwnerId", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @*@Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })*@
                @*@Html.EditorFor(model => model.OwnerId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })*@
                @Html.HiddenFor(model => model.OwnerId) @* peitsime välja lisamisvormilt*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Access, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @* Siia tegin privaatsuse (access) dropdowni, kus vaikimisi oleks valitud public *@
                @Html.DropDownListFor(model => model.Access, new List<SelectListItem>
           {
               new SelectListItem{Text="avalik", Value="public", Selected=true},
               new SelectListItem{Text="privaatne", Value="private"} } )
                @*@Html.EditorFor(model => model.Access, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })*@
                @Html.ValidationMessageFor(model => model.Access, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pildigalerii/Pildigalerii/Views/Albums/Delete.cshtml
@model Pildigalerii.Models.Album

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Access)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Access)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.FirstName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Pildigalerii/Pildigalerii/Views/Albums/Details.cshtml
@model Pildigalerii.Models.Album

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Title)</h2>

<div>
    <h4>@Html.DisplayNameFor(model => model.Person.FullName): @Html.DisplayFor(model => model.Person.FullName)</h4>

@if (HttpContext.Current.User.Identity.IsAuthenticated)  // ainult sisse loginud kasutaja
{
       <p>@Html.DisplayNameFor(model => model.Access): @Html.DisplayFor(model => model.Access)</p>
}
        <p>Loodud: @Html.DisplayFor(model => model.Created)</p>
</div>
@if (HttpContext.Current.User.Identity.IsAuthenticated)  // uue albumi saab muuta ainult sisse loginud kasutaja
{
    <p>
        @Html.ActionLink("Muuda albumi andmeid", "Edit", new { id = Model.Id })
    </p>
    <hr />
    <p>
        @Html.ActionLink("+ Lisa uus pilt", "Create", new { AlbumId = Model.Id, controller = "Posts" })
    </p>
}

<div>
    <hr />
    @foreach (var x in ViewBag.AlbumImgs) //otsib üles kõik pildid, mison albumis
    {
        <div class="gallery">
            <a href="@Url.Action("Details", "Posts", new { id = x.Id})">
                @*//lisab lingi selle pildi lehele*@
                <img src="@Url.Action("GetPicture", "Posts", new { id = x.Id})" alt=@x.Title>   @*//paneb selle lingi kuvatava pildi külge*@
            </a>
            <div class="desc">@x.Title - @x.Created</div>            @*// allapoole paneb pildi kirjelduse*@
        </div>
    }

</div>

Pildigalerii/Pildigalerii/Views/Albums/Edit.cshtml
@model Pildigalerii.Models.Album

@{
    ViewBag.Title = "Edit";
}

<h2>@Html.DisplayFor(model => model.Title)</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()



<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.OwnerId, "OwnerId", htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.EditorFor(model => model.OwnerId, new { htmlAttributes = new { @class = "form-control",type = "hidden" } })
            @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Access, "Nähtavus", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @* Siia tegin privaatsuse (access) dropdowni, kus vaikimisi oleks valitud public *@
            @Html.DropDownListFor(model => model.Access, new List<SelectListItem>
        {
            new SelectListItem{Text="avalik", Value="public", Selected=true},
            new SelectListItem{Text="privaatne", Value="private"} })
            @*@Html.EditorFor(model => model.Access, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Access, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}


<div>
    @Html.ActionLink("Kõik albumid", "Index")
</div>
<div>
    <h3>Albumis olevad pildid</h3>
    <hr />
    <p><a href="@Url.Action("Create", "Posts", new { AlbumId = Model.Id})">+ LISA PILT</a> @*// Link uue posti lisamisele*@</p>
    @foreach (var x in ViewBag.AlbumImgs) //otsib üles kõik pildid, mison albumis
    {
        <div class="gallery">
            <a href="@Url.Action("Details", "Posts", new { id = x.Id})">
                @*//lisab lingi selle pildi lehele*@
                <img src="@Url.Action("GetPicture", "Posts", new { id = x.Id})" alt=@x.Title>   @*//paneb selle lingi kuvatava pildi külge*@
            </a>
            <div class="desc">@x.Title - @x.Description</div>            @*// allapoole paneb pildi kirjelduse*@
        </div>
    }

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pildigalerii/Pildigalerii/Views/Albums/Index.cshtml
@model IEnumerable<Pildigalerii.Models.Album>

@{
    ViewBag.Title = "Index";
}

<h3>Kõik avalikud albumid</h3>

@if (HttpContext.Current.User.Identity.IsAuthenticated)  // uue albumi saab luua ainult sisse loginud kasutaja
{
<p>
    @Html.ActionLink("Loo uus album", "Create")
</p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Album", "Index", new { sortOrder = ViewBag.NameSortParm })
            @*@Html.DisplayNameFor(model => model.Title)*@
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Access)
        </th>*@
        <th>
            @Html.ActionLink("Omanik", "Index", new { sortOrder = ViewBag.OmanikSortParm })
            @*@Html.DisplayNameFor(model => model.Person.FullName)*@
        </th>
        <th>
            @Html.ActionLink("Kuupäev", "Index", new { sortOrder = ViewBag.DateSortParm })
            @*@Html.DisplayNameFor(model => model.Created)*@
        </th>

        <th></th>
    </tr>

@foreach (var item in Model)
{

    <tr>
        <td>
            @*Siia tegime selle, et albumite listis kuvatavad albumite nimed oleksid lingina, mis viivad albumi Detailsi lehele*@
            <a href="@Url.Action("Details", "Albums", new { id = item.Id })">
                @item.Title 
            </a>
            (@Html.DisplayFor(modelItem => item.Posts.Count))
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Access)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Person.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
    </tr>  
}

</table>

Pildigalerii/Pildigalerii/Views/Albums/IndexPublic.cshtml
@model IEnumerable<Pildigalerii.Models.Album>


<h3>Kõik avalikud albumid</h3>
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Person.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @*Siia tegime selle, et albumite listis kuvatavad albumite nimed oleksid lingina, mis viivad albumi Detailsi lehele*@
            <a href="@Url.Action("Details", "Albums", new { id = item.Id })">
                @item.Title
            </a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Person.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
    </tr>
}

</table>